### ISSUE TITLE
New nuget release

### ISSUE THREAD

**Issue by savornicesei** [OpenSharp/UnitWrappers#21]
Hi,
I noticed that the current nuget version is 0.6.4, released last year in Nov. while the assemblies in github have version 0.7.1 (https://github.com/OpenSharp/UnitWrappers/blob/master/src/AssemblyInfo.Version.cs).

Could you release a new nuget version? Or do you have a timeline for a new release?

Thanks.

**Comment by asd-and-Rizzo** [comment]
New assemblies are breaking change. I spitted interfaces and implementations into different assemblies as other wrappers do. There are various reasons for these. Actually I did big mistake changing big in main, instead of doing branch. I am trying to tackle this but no timeline. 
Do you miss functional in wrappers on nuget? I can try to add it and do release with these, but not big changes.

**Comment by savornicesei** [comment]
Ah, ok, so the latest version of the code source is work in progress.
Thanks!
